name: Cabin 416
favicon: null
layout_spectrum: 0.5591681159567088
typography_spectrum: 0.5481935921125114
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.18163816048763692
  lightness: 0.9931673086248338
  saturation: 0.13754555489867926
  rhythmicContrast: 0.5951285709161311
purpose: []
